// Generated by CoffeeScript 1.6.3
(function() {
  var TimeInterval, do_popup, if_going_to_popup, popup_interval, popup_url;

  TimeInterval = {};

  TimeInterval.second = 1000;

  TimeInterval.minute = 60 * TimeInterval.second;

  TimeInterval.hour = 60 * TimeInterval.minute;

  TimeInterval.day = 24 * TimeInterval.hour;

  TimeInterval.week = 24 * TimeInterval.day;

  popup_url = function() {
    return "http://catincan.com/projects/close/" + catincan_config.name + "#popup";
  };

  popup_interval = function() {
    return 2 * TimeInterval.week;
  };

  do_popup = function() {
    chrome.tabs.create({
      url: popup_url(),
      active: false
    });
    return chrome.storage.local.set({
      'last_catincan_popup': new Date().getTime()
    });
  };

  if_going_to_popup = function(callback) {
    return chrome.storage.local.get('last_catincan_popup', function(data) {
      var delta;
      delta = new Date().getTime() - data.last_catincan_popup;
      if (delta >= popup_interval()) {
        return callback();
      }
    });
  };

  if_going_to_popup(do_popup);

}).call(this);